// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yotshodiprpprkyonwno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdHNob2RpcHJwcHJreW9ud25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODUxOTksImV4cCI6MjA2NDI2MTE5OX0.NB2uGqScaOd_v4FJxt4zNrbIN3_GwDZ3qwF9_K7IKR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);